drop table if exists CONTRIBUTION;
drop table if exists DURATION;
drop table if exists TASK;
drop table if exists COLLABORATOR;

--------------------------------------------------------------
-- Collaborateurs
--------------------------------------------------------------
create table COLLABORATOR (
	CLB_ID         integer generated by default as identity(start with 1) not null,
	CLB_LOGIN      varchar(20) not null,
	CLB_FIRST_NAME varchar(20) not null,
	CLB_LAST_NAME  varchar(20) not null,
	CLB_IS_ACTIVE  boolean not null,
    constraint CLB_PK primary key (CLB_ID) 
);
create unique index CLB_LOGIN_IDX on COLLABORATOR (CLB_LOGIN);
-- set table COLLABORATOR source "COLLABORATOR.csv";
--------------------------------------------------------------
-- Taches
--------------------------------------------------------------
create table TASK (
	TSK_ID           integer     generated by default as identity(start with 1) not null,
	TSK_PATH         varchar(255) not null,
	TSK_NUMBER       varchar(  2) not null,
	TSK_CODE         varchar( 10) not null,
	TSK_NAME         varchar( 50) not null,
	TSK_BUDGET       integer      not null,
	TSK_INITIAL_CONS integer      not null,
	TSK_TODO         integer      not null,
	TSK_COMMENT      varchar(255),
    constraint TSK_PK primary key (TSK_ID)
);
create index TSK_PATH_IDX on TASK (TSK_PATH);
create unique index TSK_PATH_NUMBER_IDX on TASK (TSK_PATH, TSK_NUMBER);
create unique index TSK_PATH_CODE_IDX on TASK (TSK_PATH, TSK_CODE);
-- set table TASK source "TASK.csv";

--------------------------------------------------------------
-- Dur�es
--------------------------------------------------------------
create table DURATION (
	DUR_ID         integer not null,
	DUR_IS_ACTIVE  boolean not null,
    constraint DUR_PK primary key (DUR_ID)
);
-- set table DURATION source "DURATION.csv";

--------------------------------------------------------------
-- Contributions
--------------------------------------------------------------
create table CONTRIBUTION (
	CTB_YEAR          integer not null,
	CTB_MONTH         integer not null,
	CTB_DAY           integer not null,
	CTB_CONTRIBUTOR   integer not null,
	CTB_TASK          integer not null,
	CTB_DURATION      integer not null,
    constraint CTB_PK primary key (CTB_YEAR, CTB_MONTH, CTB_DAY, CTB_CONTRIBUTOR, CTB_TASK),
    constraint CTB_CONTRIBUTOR_FK foreign key (CTB_CONTRIBUTOR) references COLLABORATOR (CLB_ID),
    constraint CTB_TASK_FK foreign key (CTB_TASK) references TASK (TSK_ID),
    constraint CTB_DURATION_FK foreign key (CTB_DURATION) references DURATION (DUR_ID)
);
create index CTB_CONTRIBUTOR_IDX on CONTRIBUTION (CTB_CONTRIBUTOR);
create index CTB_TASK_IDX on CONTRIBUTION (CTB_TASK);
create index CTB_DURATION_IDX on CONTRIBUTION (CTB_DURATION);
