package org.activitymgr.core.orm.impl;

import java.lang.reflect.Field;

import org.activitymgr.core.orm.IConverter;
import org.activitymgr.core.orm.annotation.Table;

public class AnnotationBasedMappingConfiguration implements IMappgingConfiguration {

	@Override
	public String getSQLTableName(Class<?> theClass) {
		Table annotation = theClass.getAnnotation(Table.class);
		return annotation != null ? annotation.value() : null;
	}

	@Override
	public String getSQLColumnName(Class<?> theClass, Field attribute) {
		//theClass.getField(attributeName)
		return null;
	}

	@Override
	public String[] getPrimaryKeyAttributesName(Class<?> theClass){
		return null;
	}

	@Override
	public Field getAutoGeneratedAttribute(Class<?> theClass) {
		return null;
	}

	@Override
	public String getAttributeFormat(Class<?> theClass, Field attribute) {
		return null;
	}

	@Override
	public Class<? extends IConverter<?>> getAttributeConverter(
			Class<?> theClass, Field attribute) {
		// TODO Auto-generated method stub
		return null;
	}

}
